// This file is auto-generated by scripts/generate-asset-manifest.js
// Do not edit this file directly.
import { LibraryGroup } from './library-assets';

export const generatedLibraryGroups: LibraryGroup[] = [
  {
    "id": "fixtures",
    "name": "Fixtures",
    "categories": [
      {
        "id": "lights",
        "name": "Lights",
        "itemCount": 1,
        "icon": "/library/Fixtures/Lights/Lights.svg",
        "assets": [
          {
            "id": "lights-lights",
            "name": "Lights",
            "svgPath": "/library/Fixtures/Lights/Lights.svg"
          }
        ]
      }
    ]
  },
  {
    "id": "furniture",
    "name": "Furniture",
    "categories": [
      {
        "id": "bed",
        "name": "Bed",
        "itemCount": 6,
        "icon": "/library/Furniture/Bed/Bed-01.svg",
        "assets": [
          {
            "id": "bed-bed-01",
            "name": "Bed 01",
            "svgPath": "/library/Furniture/Bed/Bed-01.svg"
          },
          {
            "id": "bed-bed-02",
            "name": "Bed 02",
            "svgPath": "/library/Furniture/Bed/Bed-02.svg"
          },
          {
            "id": "bed-bed-03",
            "name": "Bed 03",
            "svgPath": "/library/Furniture/Bed/Bed-03.svg"
          },
          {
            "id": "bed-bed-04",
            "name": "Bed 04",
            "svgPath": "/library/Furniture/Bed/Bed-04.svg"
          },
          {
            "id": "bed-bed-05",
            "name": "Bed 05",
            "svgPath": "/library/Furniture/Bed/Bed-05.svg"
          },
          {
            "id": "bed-bed-06",
            "name": "Bed 06",
            "svgPath": "/library/Furniture/Bed/Bed-06.svg"
          }
        ]
      },
      {
        "id": "chair",
        "name": "Chair",
        "itemCount": 9,
        "icon": "/library/Furniture/Chair/Chair -01.svg",
        "assets": [
          {
            "id": "chair-chair -01",
            "name": "Chair  01",
            "svgPath": "/library/Furniture/Chair/Chair -01.svg"
          },
          {
            "id": "chair-chair -02",
            "name": "Chair  02",
            "svgPath": "/library/Furniture/Chair/Chair -02.svg"
          },
          {
            "id": "chair-chair -03",
            "name": "Chair  03",
            "svgPath": "/library/Furniture/Chair/Chair -03.svg"
          },
          {
            "id": "chair-chair -04",
            "name": "Chair  04",
            "svgPath": "/library/Furniture/Chair/Chair -04.svg"
          },
          {
            "id": "chair-chair -05",
            "name": "Chair  05",
            "svgPath": "/library/Furniture/Chair/Chair -05.svg"
          },
          {
            "id": "chair-chair -06",
            "name": "Chair  06",
            "svgPath": "/library/Furniture/Chair/Chair -06.svg"
          },
          {
            "id": "chair-chair ",
            "name": "Chair ",
            "svgPath": "/library/Furniture/Chair/Chair .svg"
          },
          {
            "id": "chair-office chair 2",
            "name": "Office Chair 2",
            "svgPath": "/library/Furniture/Chair/Office Chair 2.svg"
          },
          {
            "id": "chair-office chair",
            "name": "Office Chair",
            "svgPath": "/library/Furniture/Chair/Office Chair.svg"
          }
        ]
      },
      {
        "id": "sofa",
        "name": "Sofa",
        "itemCount": 11,
        "icon": "/library/Furniture/Sofa/Sofa-01.svg",
        "assets": [
          {
            "id": "sofa-sofa-01",
            "name": "Sofa 01",
            "svgPath": "/library/Furniture/Sofa/Sofa-01.svg"
          },
          {
            "id": "sofa-sofa-02",
            "name": "Sofa 02",
            "svgPath": "/library/Furniture/Sofa/Sofa-02.svg"
          },
          {
            "id": "sofa-sofa-03",
            "name": "Sofa 03",
            "svgPath": "/library/Furniture/Sofa/Sofa-03.svg"
          },
          {
            "id": "sofa-sofa-04",
            "name": "Sofa 04",
            "svgPath": "/library/Furniture/Sofa/Sofa-04.svg"
          },
          {
            "id": "sofa-sofa-05",
            "name": "Sofa 05",
            "svgPath": "/library/Furniture/Sofa/Sofa-05.svg"
          },
          {
            "id": "sofa-sofa-06",
            "name": "Sofa 06",
            "svgPath": "/library/Furniture/Sofa/Sofa-06.svg"
          },
          {
            "id": "sofa-sofa-07",
            "name": "Sofa 07",
            "svgPath": "/library/Furniture/Sofa/Sofa-07.svg"
          },
          {
            "id": "sofa-sofa-08",
            "name": "Sofa 08",
            "svgPath": "/library/Furniture/Sofa/Sofa-08.svg"
          },
          {
            "id": "sofa-sofa-09",
            "name": "Sofa 09",
            "svgPath": "/library/Furniture/Sofa/Sofa-09.svg"
          },
          {
            "id": "sofa-sofa-10",
            "name": "Sofa 10",
            "svgPath": "/library/Furniture/Sofa/Sofa-10.svg"
          },
          {
            "id": "sofa-sofa-11",
            "name": "Sofa 11",
            "svgPath": "/library/Furniture/Sofa/Sofa-11.svg"
          }
        ]
      }
    ]
  }
];
